#!/bin/sh

if [ ! -f $HOME/.local/bin/pipenv ]; then
    echo 'pipenv python pip package does not installed, Install it by running:'
    echo 'pip install pipenv --user'
    echo 'then add this line to $HOME/.bashrc:'
    echo 'export PATH="${HOME}/.local/bin:$PATH"'
    echo 'then issue this command:'
    echo 'source $HOME/.bashrc'
    exit 0
fi

if [ ! -f $(cd "$(dirname "$0")" && pwd)/.env ]; then
    echo "$(cd "$(dirname "$0")" && pwd)/.env file not found!"
    echo "Create it by running:"
    echo "    cp $(cd "$(dirname "$0")" && pwd)/.env-template $(cd "$(dirname "$0")" && pwd)/.env"
    echo "Then use your favorite editor to edit things like: Postgres database password, etc."
    exit 0
fi

if [ ! -f /usr/bin/direnv ]; then
    echo 'direnv apt package does not installed, Install it by running:'
    echo 'sudo apt install direnv'
    echo 'then add this line to $HOME/.bashrc:'
    echo 'eval "$(direnv hook bash)"'
    echo 'then issue this command:'
    echo 'source $HOME/.bashrc'
    exit 0
fi


export PIPENV_VENV_IN_PROJECT="enabled"
cd "$(dirname "$0")" && $HOME/.local/bin/pipenv install

ln -sf $(cd "$(dirname "$0")" && pwd)/bin/direxec $(cd "$(dirname "$0")" && pwd)/common/build
ln -sf $(cd "$(dirname "$0")" && pwd)/bin/direxec $(cd "$(dirname "$0")" && pwd)/common/entrypoint
ln -sfT $(cd "$(dirname "$0")" && pwd)/lib/doodbalib $(cd "$(dirname "$0")" && pwd)/.venv/local/lib/python2.7/site-packages/doodbalib
ln -sfT $(cd "$(dirname "$0")" && pwd)/lib/doodbalib $(cd "$(dirname "$0")" && pwd)/.venv/local/lib/python2.7/site-packages/odoobaselib
ln -sf $(cd "$(dirname "$0")" && pwd)/bin/* $(cd "$(dirname "$0")" && pwd)/.venv/bin/
# set permissions
chmod 750 $(cd "$(dirname "$0")" && pwd)
chmod 600 $(cd "$(dirname "$0")" && pwd)/.env
chmod 750 $(cd "$(dirname "$0")" && pwd)/auto
chmod 750 $(cd "$(dirname "$0")" && pwd)/auto/addons
chmod 750 $(cd "$(dirname "$0")" && pwd)/bin
chmod 740 $(cd "$(dirname "$0")" && pwd)/bin/*
chmod 750 $(cd "$(dirname "$0")" && pwd)/common
chmod 750 $(cd "$(dirname "$0")" && pwd)/common/build.d
chmod 740 $(cd "$(dirname "$0")" && pwd)/common/build.d/*
chmod 750 $(cd "$(dirname "$0")" && pwd)/common/conf.d
chmod -f 640 $(cd "$(dirname "$0")" && pwd)/common/conf.d/odoo.cfg
chmod 750 $(cd "$(dirname "$0")" && pwd)/common/entrypoint.d
chmod 740 $(cd "$(dirname "$0")" && pwd)/common/entrypoint.d/*
chmod 750 $(cd "$(dirname "$0")" && pwd)/custom
chmod 750 $(cd "$(dirname "$0")" && pwd)/custom/src
chmod 750 $(cd "$(dirname "$0")" && pwd)/custom/src/private/
chmod -f 640 $(cd "$(dirname "$0")" && pwd)/custom/src/addons.yaml
chmod -f 640 $(cd "$(dirname "$0")" && pwd)/custom/src/repos.yaml
chmod 750 $(cd "$(dirname "$0")" && pwd)/lib
chmod 750 $(cd "$(dirname "$0")" && pwd)/lib/doodbalib
chmod 740 $(cd "$(dirname "$0")" && pwd)/lib/doodbalib/*
chmod 750 $(cd "$(dirname "$0")" && pwd)/qa
chmod 750 $(cd "$(dirname "$0")" && pwd)/qa/artifacts
chmod -f 600 $(cd "$(dirname "$0")" && pwd)/.env
chmod 600 $(cd "$(dirname "$0")" && pwd)/.env-template
chmod -f 600 $(cd "$(dirname "$0")" && pwd)/.envrc
chmod 600 $(cd "$(dirname "$0")" && pwd)/.envrc-template
chmod 740 $(cd "$(dirname "$0")" && pwd)/bootstrap
chmod 740 $(cd "$(dirname "$0")" && pwd)/build
chmod 740 $(cd "$(dirname "$0")" && pwd)/install
chmod -f 600 $(cd "$(dirname "$0")" && pwd)/Pipfile
chmod -f 600 $(cd "$(dirname "$0")" && pwd)/Pipfile.lock
chmod 740 $(cd "$(dirname "$0")" && pwd)/run
