#!/bin/sh

if [ ! -f /usr/bin/direnv ]; then
    echo 'direnv apt package does not installed, Install it by running:'
    echo 'sudo apt install direnv'
    echo 'then add this line to $HOME/.bashrc:'
    echo 'eval "$(direnv hook bash)"'
    echo 'then issue this command:'
    echo 'source $HOME/.bashrc'
    exit 0
fi

if [ ! -f $(cd "$(dirname "$0")" && pwd)/.envrc ]; then
    echo "$(cd "$(dirname "$0")" && pwd)/.envrc file not found!"
    echo "Create it by running:"
    echo "Copy it from $(cd "$(dirname "$0")" && pwd)/templates/"
    echo "Then use your favorite editor to edit things like: Postgres database password, etc."
    exit 0
fi

if [ ! -f $(cd "$(dirname "$0")" && pwd)/common/conf.d/odoo.cfg ]; then
    echo "$(cd "$(dirname "$0")" && pwd)/common/conf.d/odoo.cfg file not found!"
    echo "Copy it from $(cd "$(dirname "$0")" && pwd)/templates/"
    exit 0
fi

if [ ! -f $(cd "$(dirname "$0")" && pwd)/requirements.txt ]; then
    echo "$(cd "$(dirname "$0")" && pwd)/requirements.txt file not found!"
    echo "Copy it from $(cd "$(dirname "$0")" && pwd)/templates/"
    exit 0
fi

if [ ! -d $(cd "$(dirname "$0")" && pwd)/.venv ]; then
    if [ $(echo $ODOO_VERSION | cut -d '.' -f1) -le 10 ]; then
        python2 -m virtualenv $(cd "$(dirname "$0")" && pwd)/.venv
    else
        python3 -m virtualenv $(cd "$(dirname "$0")" && pwd)/.venv
    fi
fi

ln -sf $(cd "$(dirname "$0")" && pwd)/bin/direxec $(cd "$(dirname "$0")" && pwd)/common/build
ln -sf $(cd "$(dirname "$0")" && pwd)/bin/direxec $(cd "$(dirname "$0")" && pwd)/common/entrypoint
ln -sf $(cd "$(dirname "$0")" && pwd)/lib/doodbalib $(cd "$(dirname "$0")" && pwd)/.venv/lib/*/site-packages/
ln -sf $(cd "$(dirname "$0")" && pwd)/lib/doodbalib $(cd "$(dirname "$0")" && pwd)/.venv/lib/*/site-packages/
ln -sf $(cd "$(dirname "$0")" && pwd)/bin/* $(cd "$(dirname "$0")" && pwd)/.venv/bin/
# set permissions
chmod 750 $(cd "$(dirname "$0")" && pwd)
chmod 750 $(cd "$(dirname "$0")" && pwd)/auto
chmod 750 $(cd "$(dirname "$0")" && pwd)/auto/addons
chmod 750 $(cd "$(dirname "$0")" && pwd)/bin
chmod 740 $(cd "$(dirname "$0")" && pwd)/bin/*
chmod 750 $(cd "$(dirname "$0")" && pwd)/common
chmod 750 $(cd "$(dirname "$0")" && pwd)/common/build.d
chmod 740 $(cd "$(dirname "$0")" && pwd)/common/build.d/*
chmod 750 $(cd "$(dirname "$0")" && pwd)/common/conf.d
chmod -f 640 $(cd "$(dirname "$0")" && pwd)/common/conf.d/odoo.cfg
chmod 750 $(cd "$(dirname "$0")" && pwd)/common/entrypoint.d
chmod 740 $(cd "$(dirname "$0")" && pwd)/common/entrypoint.d/*
chmod 750 $(cd "$(dirname "$0")" && pwd)/custom
chmod 750 $(cd "$(dirname "$0")" && pwd)/custom/src
chmod 750 $(cd "$(dirname "$0")" && pwd)/custom/src/private/
chmod -f 640 $(cd "$(dirname "$0")" && pwd)/custom/src/addons.yaml
chmod -f 640 $(cd "$(dirname "$0")" && pwd)/custom/src/repos.yaml
chmod 750 $(cd "$(dirname "$0")" && pwd)/lib
chmod 750 $(cd "$(dirname "$0")" && pwd)/lib/doodbalib
chmod 740 $(cd "$(dirname "$0")" && pwd)/lib/doodbalib/*
chmod 750 $(cd "$(dirname "$0")" && pwd)/qa
chmod 750 $(cd "$(dirname "$0")" && pwd)/qa/artifacts
chmod 640 $(cd "$(dirname "$0")" && pwd)/templates/*
chmod -f 600 $(cd "$(dirname "$0")" && pwd)/.envrc
chmod 740 $(cd "$(dirname "$0")" && pwd)/bootstrap
chmod 740 $(cd "$(dirname "$0")" && pwd)/build
chmod 740 $(cd "$(dirname "$0")" && pwd)/install
chmod 640 $(cd "$(dirname "$0")" && pwd)/requirements.txt
chmod 740 $(cd "$(dirname "$0")" && pwd)/run

