#!/bin/sh

if [ ! -f $HOME/.local/bin/pipenv ]; then
    echo 'pipenv python pip package does not installed, Install it by running:'
    echo 'pip install pipenv --user'
    echo 'then add this line to $HOME/.bashrc:'
    echo 'export PATH="${HOME}/.local/bin:$PATH"'
    echo 'then issue this command:'
    echo 'source $HOME/.bashrc'
    exit 0
fi

if [ ! -f $(cd "$(dirname "$0")" && pwd)/.env ]; then
    echo "$(cd "$(dirname "$0")" && pwd)/.env file not found!"
    echo "Create it by running:"
    echo "    cp $(cd "$(dirname "$0")" && pwd)/.env-template $(cd "$(dirname "$0")" && pwd)/.env"
    echo "Then use your favorite editor to edit things like: Postgres database password, etc."
    exit 0
fi

if [ ! -f /usr/bin/direnv ]; then
    echo 'direnv apt package does not installed, Install it by running:'
    echo 'sudo apt install direnv'
    echo 'then add this line to $HOME/.bashrc:'
    echo 'eval "$(direnv hook bash)"'
    echo 'then issue this command:'
    echo 'source $HOME/.bashrc'
    exit 0
fi

cd "$(dirname "$0")" && /usr/bin/direnv exec . /bin/bash -c '$HOME/.local/bin/pipenv run ./common/build && $HOME/.local/bin/pipenv run ./common/entrypoint'