#!/bin/sh
  
. $(cd "$(dirname "$0")" && pwd)/.venv/bin/activate

pip install -r requirements.txt

cd "$(dirname "$0")" && /usr/bin/direnv exec . /bin/bash -c './common/build && ./common/entrypoint'

deactivate
