#!/bin/sh

SCRIPT_PATH=$(cd "$(dirname "$0")" && pwd)
cd $SCRIPT_PATH

. $SCRIPT_PATH/.venv/bin/activate

rm -fr ./auto/odoo.conf
rm -fr ./auto/addons/*
/bin/bash -c "$(/bin/ls -1 ./custom/src | grep -Ev 'private|repos.yaml|addons.yaml' | /usr/bin/awk '{print("rm -fr ./custom/src/" $1)}')"

pip install -r requirements.txt

cd "$(dirname "$0")" && /usr/bin/direnv exec . /bin/bash -c './common/build'
cd $SCRIPT_PATH
cd "$(dirname "$0")" && /usr/bin/direnv exec . /bin/bash -c './common/entrypoint'

deactivate
