#!/bin/sh

if [ $# -eq 0 ]; then
  echo "Installs a new empty demo database"
  echo "Usage: ./install [databasename]"
  exit
fi

createdb "$1"
cd "$(dirname "$0")"
. ./.venv/bin/activate

odoo -i base -d "$1" --stop-after-init

deactivate
