#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
from glob import iglob

from doodbalib import (
    addons_config,
    ADDONS_DIR,
    ADDONS_YAML,
    logger,
    SRC_DIR,
)

# Update system varibles
with open(os.path.join(os.environ.get("ODOO_WORK_DIR"), 'odoo-variables')) as variablesource:
    for line in variablesource:
        if 'export' not in line:
            continue
        if line.startswith('#'):
            continue
        if line.startswith('export PATH'):
            continue
        # Remove `"` and `export `
        # then, split name / value pair
        key, value = line.replace('"', '', 2).replace('export ', '', 1).strip().split('=', 1)
        os.environ[key] = value

logger.info(
    "Linking all addons from %s in %s",
    ADDONS_YAML,
    ADDONS_DIR)

# Remove all links in addons dir
for link in iglob(os.path.join(ADDONS_DIR, "*")):
    os.remove(link)
# Add new links
for addon, repo in addons_config():
    src = os.path.relpath(os.path.join(SRC_DIR, repo, addon), ADDONS_DIR)
    dst = os.path.join(ADDONS_DIR, addon)
    os.symlink(src, dst)
    logger.debug("Linked %s in %s", src, dst)
