#!/usr/bin/env python
# Copyright 2017 LasLabs Inc.

import os

from os.path import basename, join, splitext
from glob import glob

from doodbalib import (
    CUSTOM_DIR,
    FILE_APT_BUILD,
    SRC_DIR,
)
from doodbalib.installer import install, INSTALLERS, logger

# Update system varibles
with open(os.path.join(os.environ.get("ODOO_WORK_DIR"), 'odoo-variables')) as variablesource:
    for line in variablesource:
        if 'export' not in line:
            continue
        if line.startswith('#'):
            continue
        if line.startswith('export PATH'):
            continue
        # Remove `"` and `export `
        # then, split name / value pair
        key, value = line.replace('"', '', 2).replace('export ', '', 1).strip().split('=', 1)
        os.environ[key] = value

# Build dependencies installed before any others
install("apt", FILE_APT_BUILD)

for name in INSTALLERS:
    req_files = []
    # Normal dependency installation
    req_files.append(join(CUSTOM_DIR, 'dependencies', '%s.txt' % name))
    for req_file in req_files:
        install(name, req_file)

# Sorted dependencies installation
dep_files = sorted(glob(join(CUSTOM_DIR, 'dependencies', '[0-9]*-*')))
for dep_file in dep_files:
    root, ext = splitext(basename(dep_file))
    # Get the installer (xxx-installer[-description][.ext])
    installer = root.split('-', 2)[1]
    if installer not in INSTALLERS:
        logger.error("Unknown installer: %s", installer)
        raise Exception
    install(installer, dep_file)
