#!/bin/bash
source $ODOO_WORK_DIR/odoo-variables
set -e
src=$ODOO_WORK_DIR/custom/src/odoo
log INFO Installing Odoo from $src

# For development you could want to avoid installing Odoo to speed up build
if [ "$PIP_INSTALL_ODOO" == true ]; then
    args="--no-cache-dir"
    # Odoo v8 dependencies could crash at install, so we don't use them
    if [ "$ODOO_VERSION" == "8.0" ]; then
        args="$args --no-deps"
    fi
    if [ "$ODOO_VERSION" == "8.0" -o "$ODOO_VERSION" == "9.0" -o "$ODOO_VERSION" == "10.0" ]; then
        pip install --user $args --editable $src
    fi
    if [ "$ODOO_VERSION" == "11.0" -o "$ODOO_VERSION" == "12.0" ]; then
        pip3 install --user $args --editable $src
    fi

    # Make version 8.0 and 9.0 have an `odoo` executable
    if [ "$ODOO_VERSION" == "8.0" -o "$ODOO_VERSION" == "9.0" ]; then
        rm -fr $HOME/.local/bin/odoo
        ln -s $HOME/.local/bin/odoo.py $HOME/.local/bin/odoo
    fi
else
    log WARNING Blindly symlinking odoo executable
    if [ "$ODOO_VERSION" == "8.0" -o "$ODOO_VERSION" == "9.0" ]; then
        rm -fr $HOME/.local/bin/odoo
        ln -s $HOME/.local/bin/odoo.py $HOME/.local/bin/odoo
    fi
fi
